.TH "geom-sinestar" "1" "4 May 2012" "version 0.1"
.SH NAME
geom sinestar
.SH DESCRIPTION
Create a sine star.
.SH USAGE
geom sinestar -l 0.9 -n 12 -p 1000 -w 500 -h 500 -g "POINT (100 100)"
.SH OPTIONS
-n --numberOfArms: The number of arms
.PP
-l --armLengthRatio: The arm length ratio
.PP
-w --width: The width
.PP
-h --height: The height
.PP
-p --numberOfPoints: The number of points
.PP
-r --rotation: The rotation
.PP
-c --center: The flag to use center (true) or the base (false)
.PP
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
