.TH "geom-node" "1" "4 May 2012" "version 0.1"
.SH NAME
geom node
.SH DESCRIPTION
Node the linestrings from the input geometry.
.SH USAGE
geom node -g "LINESTRING (5 51, 8 54, 12 50, 8 47, 10 55, 7 52, 5 53, 6 51)" -n 5
.SH OPTIONS
-n --number: The number of decimal places
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
