.TH "geom-narrow" "1" "4 May 2012" "version 0.1"
.SH NAME
geom narrow
.SH DESCRIPTION
Convert a geometry collection to it's most specific type.
.SH USAGE
geom narrow -g "GEOMETRYCOLLECTION (POINT (1 1), POINT(10 10))"
.SH OPTIONS
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
