.TH "geom-centroid" "1" "24 February 2014" "version 0.1"
.SH NAME
geom slice
.SH DESCRIPTION
Get a subset of geometries from a geometry collection.
.SH USAGE
geom slice -g "MULTIPOINT ((1 1), (2 2), (3 3), (4 4), (5 5))" -s 1 -e 4
.SH OPTIONS
-g --geometry: The input geometry
.PP
-s --start: The start index
.PP
-e --end: The end index
.PP
--help : Print help message
.PP
