.TH "geom-scale" "1" "4 May 2012" "version 0.1"
.SH NAME
geom scale
.SH DESCRIPTION
Create a new geometry by scaling the input geometry
.SH USAGE
geom scale -g "POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))" -s 2 -t 5
.SH OPTIONS
-s --xscale: The value to scale by in the x direction
.PP
-t --yscale: The value to scale by in the y direction
.PP
-x --xcoordinate: The x-ordinate of the point to scale around
.PP
-y --ycoordinate: The y-ordinate of the point to scale around
.PP
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
