.TH "geom-fromwkb" "1" "4 May 2012" "version 0.1"
.SH NAME
geom fromwkb
.SH DESCRIPTION
Convert a WKB to a WKT Geometry.
.SH USAGE
geom fromwkb -b 00000000013FF00000000000004000000000000000
.SH OPTIONS
-b --wkb: The WKB text
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
