.TH "geom-mortoncurve" "1" "4 May 2012" "version 0.1"
.SH NAME
geom mortoncurve
.SH DESCRIPTION
Create a morton curve.
.SH USAGE
geom mortoncurve -g "POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))" -n 54
.SH OPTIONS
-n --number: The number of points.
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
