.TH "geom-coordinates" "1" "4 May 2012" "version 0.1"
.SH NAME
geom coordinates
.SH DESCRIPTION
Get the coordinates of the geometry.
.SH USAGE
geom coordinates -g "POLYGON ((1 1, 1 10, 10 10, 10 1, 1 1))"
.SH OPTIONS
-u --unique: The flag to only include unique coordinates
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
