.TH "geom-touches" "1" "4 May 2012" "version 0.1"
.SH NAME
geom touches
.SH DESCRIPTION
Determine if the input geometry touches another geometry.
.SH USAGE
geom touches -g "POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))" -o "POLYGON ((10 10, 10 14, 14 14, 14 10, 10 10))"
.SH OPTIONS
-o --otherGeometry: The other geometry
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
