.TH "geom-covers" "1" "4 May 2012" "version 0.1"
.SH NAME
geom covers
.SH DESCRIPTION
Determine whether the first geometry covers the other geometry.
.SH USAGE
geom covers -g "POLYGON ((1 1, 1 10, 10 10, 10 1, 1 1))" -o "POINT (2 2)"
.SH OPTIONS
-o --otherGeometry: The other geometry
.PP
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
