.TH "geom-pointsalong" "1" "4 May 2012" "version 0.1"
.SH NAME
geom pointsalong
.SH DESCRIPTION
Place points along a line
.SH USAGE
geom pointsalong -g "LINESTRING (0 0, 10 10)" -d 1
.SH OPTIONS
-d --distance: The distance between points
.PP
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
