.TH "geom-dump" "1" "4 May 2012" "version 0.1"
.SH NAME
geom dump
.SH DESCRIPTION
Put each geometry from a GeometryCollection on it's own line.
.SH USAGE
geom dump -g "MULTIPOINT (1 1, 2 2)"
.SH OPTIONS
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
