.TH "geom-buffer" "1" "4 May 2012" "version 0.1"
.SH NAME
geom buffer
.SH DESCRIPTION
Buffer a geometry by a distance.
.SH USAGE
geom buffer -g "POINT (1 1)" -d 10
.SH OPTIONS
-d --distance: The buffer distance
.PP
-q --quadrantSegments: The number of quadrant segments
.PP
-c --endCapStyle: The end cap style (round, flat/butt, square)
.PP
-s --singleSided: The flag for whether the buffer should be single sided
.PP
-f --simplifyFactor: The simplify factor
.PP
-m --mitreLimit: The mitre limit
.PP
-j --joinStyle: The join style (round, mitre, bevel)
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
