.TH "geom-startpoint" "1" "4 May 2012" "version 0.1"
.SH NAME
geom startpoint
.SH DESCRIPTION
Get the start point of a LineString or MultiLineString.
.SH USAGE
geom startpoint -g "LINESTRING (1 1, 5 5, 10 10)"
.SH OPTIONS
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
