.TH "geom-project" "1" "4 May 2012" "version 0.1"
.SH NAME
geom project
.SH DESCRIPTION
Project the input geometry from one coordinate system to another.
.SH USAGE
geom project -g "POINT (1179931.55 645310.31)" -s EPSG:2927 -t EPSG:4326 
.SH OPTIONS
-s --source: The source projection
.PP
-t --target: The target projection
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
