.TH "geom-split" "1" "4 May 2012" "version 0.1"
.SH NAME
geom split
.SH DESCRIPTION
Split a Geometry by another Geometry
.SH USAGE
geom split -g "POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))" -o "LINESTRING (0 0, 10 10)"
.SH OPTIONS
-o --otherGeometry: The other geometry
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
