.TH "geom-angle" "1" "7 October 2013" "version 0.2"
.SH NAME
geom angle
.SH DESCRIPTION
Calculate the angle between two points
.SH USAGE
geom angle -g "POINT (1 1)" -o "POINT (10 10)" -t degrees
.SH OPTIONS
-g --geometry: The first Point
.PP
-o --otherGeometry: The second Point
.PP
-t --type: The output units (degrees or radians)
.PP
--help : Print help message
.PP
