.TH "geom-pipe" "1" "4 May 2012" "version 0.1"
.SH NAME
geom pipe
.SH DESCRIPTION
Combine multiple commands together with a pipe.
.SH USAGE
geom pipe -c "buffer -g 'POINT(1 1)' -d 10 | centroid"
.SH OPTIONS
-c --commands: Commands separate by pipe
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
