.TH "geom-kochsnowflake" "1" "4 May 2012" "version 0.1"
.SH NAME
geom kochsnowflake
.SH DESCRIPTION
Generate a koch snow flake.
.SH USAGE
geom kochsnowflake -g "POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))" -n 100
.SH OPTIONS
-n --number: The number of points.
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
