.TH "geom-intersects" "1" "4 May 2012" "version 0.1"
.SH NAME
geom intersects
.SH DESCRIPTION
Determine if the first geometry intersects the second geometry.
.SH USAGE
geom intersects -g "POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))" -o "POLYGON ((5 5, 5 15, 15 15, 15 5, 5 5))"
.SH OPTIONS
-o --otherGeometry: The other geometry
.PP
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
