.TH "geom-isvalid" "1" "4 May 2012" "version 0.1"
.SH NAME
geom isvalid
.SH DESCRIPTION
Determine if the input geometry is valid or not.
.SH USAGE
geom isvalid -g "POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))"
.SH OPTIONS
-t --type: The flag to show the validation error message, the error location, or validity (msg, loc, or val)
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
