.TH "geom-largestemptycircle" "1" "4 May 2012" "version 0.1"
.SH NAME
geom largestemptycircle
.SH DESCRIPTION
Calculate the largest empty circle.
.SH USAGE
geom largestemptycircle -g "MULTIPOINT ((-122.3935317993164 47.57571508225466),(-122.38838195800781 47.57444120741259),(-122.39061355590819 47.5823155737249))"
.SH OPTIONS
-t --tolerance: The tolerance
.PP
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
