.TH "geom-convexHull" "1" "4 May 2012" "version 0.1"
.SH NAME
geom convexHull
.SH DESCRIPTION
Calculate the convex hull of a Geometry.
.SH USAGE
geom convexhull -g "POLYGON ((9 52, 9 50, 7 50, 7 48, 10 47, 10 46, 13 46, 11 52, 10 52, 9 52))"
.SH OPTIONS
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
