.TH "geom-pointatangle" "1" "4 May 2012" "version 0.1"
.SH NAME
geom pointatangle
.SH DESCRIPTION
Calculate a point at a given angle distance from the input point.
.SH USAGE
geom pointatangle -g "POINT (10 10)" -a 90 -d 10
.SH OPTIONS
-d --distance: The distance
.PP
-a --angle: The angle (in degrees)
.PP
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
