.TH "geom-endpoint" "1" "4 May 2012" "version 0.1"
.SH NAME
geom endpoint
.SH DESCRIPTION
Get the end point of a LineString or a MultiLineString.
.SH USAGE
geom endpoint -g "LINESTRING (1 1, 5 5, 10 10)"
.SH OPTIONS
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
