.TH "geom-envelope" "1" "4 May 2012" "version 0.1"
.SH NAME
geom envelope
.SH DESCRIPTION
Calculate the envelope of a Geometry.
.SH USAGE
geom envelope -g "POLYGON ((9 52, 9 50, 7 50, 7 48, 10 47, 10 46, 13 46, 11 52, 10 52, 9 52))"
.SH OPTIONS
-e --expandBy: The distance to expand the Envelope
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
