.TH "geom-randomwalk" "1" "4 May 2012" "version 0.1"
.SH NAME
geom randomwalk
.SH DESCRIPTION
Generate a random walk as a linestring.
.SH USAGE
geom randomwalk -n 100 -a 45 -d 10 -g "POINT (1 1)" 
.SH OPTIONS
-n --number: The number of walks
.PP
-d --distance: The distance between Coordinates
.PP
-p --probability: The probability of changing direction
.PP
-a --angle: The angle increment (in degrees) when changing direction
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
