.TH "geom-supercircle" "1" "4 May 2012" "version 0.1"
.SH NAME
geom supercircle
.SH DESCRIPTION
Create a super circle.
.SH USAGE
geom supercircle -g "POINT (100 100)" -p 30 -w 500 -h 500
.SH OPTIONS
-p --power: The positive power
.PP
-w --width: The width
.PP
-h --height: The height
.PP
-p --numberOfPoints: The number of points
.PP
-r --rotation: The rotation
.PP
-c --center: The flag to use center (true) or the base (false)
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
