.TH "geom-minrect" "1" "4 May 2012" "version 0.1"
.SH NAME
geom minrect
.SH DESCRIPTION
Calculate the minimum rectangle of the input geometry.
.SH USAGE
geom minrect -g "POLYGON ((16 51, 7 53, 12 46, 5 41, 12 41, 16 51))"
.SH OPTIONS
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
--web-help : Open help in a web browser
.PP
