.TH "geom-interiorpoint" "1" "4 May 2012" "version 0.1"
.SH NAME
geom interiorpoint
.SH DESCRIPTION
Calculate the interior point of the input geometry.
.SH USAGE
geom interiorpoint -g "POLYGON ((8 54, 8 51, 14 51, 14 47, 7 47, 7 42, 17 45, 16 53, 13 53, 8 54))"
.SH OPTIONS
-g --geometry: The input geometry
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
