.TH "geom-split" "1" "14 Sep 2013" "version 0.3"
.SH NAME
geom split
.SH DESCRIPTION
Split the input Geometry by the other Geometry.
.SH USAGE
geom split -g "POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))" -o "LINESTRING (0 0, 10 10)"
.SH OPTIONS
-o --otherGeometry: The other geometry
.PP
-g --geometry: The input geometry
.PP
--help : Print help message
.PP
