.TH "geom-text" "1" "4 May 2012" "version 0.1"
.SH NAME
geom text
.SH DESCRIPTION
Create a geometry from a string.
.SH USAGE
geom text -t "JTS"
.SH OPTIONS
-t --text: The text
.PP
-f --fontName: The font name
.PP
-s --pointSize: The font size
.PP
--help: Print help message
.PP
--web-help: Open help in a web browser
.PP
